# Auto Generated
item_event_names = [
    "Aged Roe",
    "Any Egg",
    "Any Fish",
    "Artifact Trove",
    "Bait",
    "Basic Fertilizer",
    "Quality Fertilizer",
    "Deluxe Fertilizer",
    "Tree Fertilizer",
    "Bat Wing",
    "Battery Pack",
    "Bee House",
    "Beer",
    "Blackberry",
    "Bomb",
    "Bone Fragment",
    "Bouquet",
    "Bread",
    "Broken CD",
    "Broken Glasses",
    "Bug Meat",
    "Cactus Fruit",
    "Cask",
    "Cave Carrot",
    "Caviar",
    "Chanterelle",
    "Cheese Press",
    "Cheese",
    "Cherry Bomb",
    "Chicken",
    "Chicken Egg",
    "Cinder Shard",
    "Clam",
    "Clay",
    "Cloth",
    "Coal",
    "Cockle",
    "Coconut",
    "Coffee",
    "Coffee Maker",
    "Common Mushroom",
    "Copper Bar",
    "Copper Ore",
    "Coral",
    "Cow",
    "Cow Milk",
    "Crab",
    "Crab Pot",
    "Crayfish",
    "Crocus",
    "Crystal Fruit",
    "Daffodil",
    "Dandelion",
    "Dinosaur",
    "Dragon Tooth",
    "Dried Starfish",
    "Driftwood",
    "Duck Egg",
    "Duck Feather",
    "Duck",
    "Egg",
    "Egg (Brown)",
    "Energy Tonic",
    "Fiber",
    "Fiddlehead Fern",
    "Magic Rock Candy",
    "Fishing Chest",
    "Flute Block",
    "Frozen Geode",
    "Furnace",
    "Geode",
    "Ginger",
    "Goat Cheese",
    "Goat Milk",
    "Goat",
    "Gold Bar",
    "Gold Ore",
    "Golden Coconut",
    "Golden Pumpkin",
    "Green Algae",
    "Green Tea",
    "Hardwood",
    "Hay",
    "Hazelnut",
    "Holly",
    "Honey",
    "Hot Java Ring",
    "Ice Cream",
    "Iridium Bar",
    "Iridium Ore",
    "Iron Bar",
    "Iron Ore",
    "Jelly",
    "Joja Cola",
    "JotPK Small Buff",
    "JotPK Medium Buff",
    "JotPK Big Buff",
    "JotPK Max Buff",
    "Juice",
    "Junimo Kart Small Buff",
    "Junimo Kart Medium Buff",
    "Junimo Kart Big Buff",
    "Junimo Kart Max Buff",
    "Keg",
    "Large Egg",
    "Large Egg (Brown)",
    "Large Goat Milk",
    "Large Milk",
    "Leek",
    "Life Elixir",
    "Lightning Rod",
    "Lobster",
    "Loom",
    "Magma Cap",
    "Magma Geode",
    "Maple Syrup",
    "Mayonnaise",
    "Mayonnaise Machine",
    "Mead",
    "Mega Bomb",
    "Mermaid's Pendant",
    "Milk",
    "Monster Musk",
    "Morel",
    "Muscle Remedy",
    "Mussel",
    "Mussel Node",
    "Nautilus Shell",
    "Oak Resin",
    "Oil",
    "Oil Maker",
    "Oil of Garlic",
    "Omni Geode",
    "Ostrich",
    "Ostrich Egg",
    "Ostrich Incubator",
    "Oyster",
    "Pale Ale",
    "Pearl",
    "Periwinkle",
    "Pickles",
    "Pig",
    "Piña Colada",
    "Pine Tar",
    "Pizza",
    "Preserves Jar",
    "Purple Mushroom",
    "Rabbit",
    "Rabbit's Foot",
    "Radioactive Ore",
    "Radioactive Bar",
    "Rainbow Shell",
    "Rain Totem",
    "Recycling Machine",
    "Red Mushroom",
    "Refined Quartz",
    "Rice",
    "Roe",
    "Salad",
    "Salmonberry",
    "Sap",
    "Scarecrow",
    "Sea Urchin",
    "Seaweed",
    "Secret Note",
    "Seed Maker",
    "Sheep",
    "Shrimp",
    "Slime",
    "Any Slingshot",
    "Snail",
    "Snow Yam",
    "Soggy Newspaper",
    "Solar Essence",
    "Solar Panel",
    "Spaghetti",
    "Spice Berry",
    "Spring Onion",
    "Squid Ink",
    "Staircase",
    "Stone",
    "Strange Bun",
    "Sturgeon Roe",
    "Sugar",
    "Sweet Pea",
    "Tapper",
    "Tea Leaves",
    "Tea Sapling",
    "Trash",
    "Triple Shot Espresso",
    "Truffle Oil",
    "Truffle",
    "Vinegar",
    "Void Egg",
    "Void Essence",
    "Void Mayonnaise",
    "Wheat Flour",
    "White Algae",
    "Wild Horseradish",
    "Wild Plum",
    "Wilted Bouquet",
    "Wine",
    "Winter Root",
    "Wood",
    "Wool",
    "Worm Bin",
    "Albacore",
    "Anchovy",
    "Blue Discus",
    "Bream",
    "Bullhead",
    "Carp",
    "Catfish",
    "Chub",
    "Dorado",
    "Eel",
    "Flounder",
    "Ghostfish",
    "Halibut",
    "Herring",
    "Ice Pip",
    "Largemouth Bass",
    "Lava Eel",
    "Lingcod",
    "Lionfish",
    "Midnight Carp",
    "Octopus",
    "Perch",
    "Pike",
    "Pufferfish",
    "Rainbow Trout",
    "Red Mullet",
    "Red Snapper",
    "Salmon",
    "Sandfish",
    "Sardine",
    "Scorpion Carp",
    "Sea Cucumber",
    "Shad",
    "Slimejack",
    "Smallmouth Bass",
    "Squid",
    "Stingray",
    "Stonefish",
    "Sturgeon",
    "Sunfish",
    "Super Cucumber",
    "Tiger Trout",
    "Tilapia",
    "Tuna",
    "Void Salmon",
    "Walleye",
    "Woodskip",
    "Blobfish",
    "Midnight Squid",
    "Spook Fish",
    "Angler",
    "Crimsonfish",
    "Glacierfish",
    "Legend",
    "Mutant Carp",
    "Dwarf Scroll I",
    "Dwarf Scroll II",
    "Dwarf Scroll III",
    "Dwarf Scroll IV",
    "Chipped Amphora",
    "Arrowhead",
    "Ancient Doll",
    "Elvish Jewelry",
    "Chewing Stick",
    "Ornamental Fan",
    "Dinosaur Egg",
    "Rare Disc",
    "Ancient Sword",
    "Rusty Spoon",
    "Rusty Spur",
    "Rusty Cog",
    "Chicken Statue",
    "Ancient Seed",
    "Prehistoric Tool",
    "Anchor",
    "Glass Shards",
    "Bone Flute",
    "Prehistoric Handaxe",
    "Dwarvish Helm",
    "Dwarf Gadget",
    "Ancient Drum",
    "Golden Mask",
    "Golden Relic",
    "Strange Doll (Green)",
    "Strange Doll",
    "Prehistoric Scapula",
    "Prehistoric Tibia",
    "Prehistoric Skull",
    "Skeletal Hand",
    "Prehistoric Rib",
    "Prehistoric Vertebra",
    "Skeletal Tail",
    "Nautilus Fossil",
    "Amphibian Fossil",
    "Palm Fossil",
    "Trilobite",
    "Quartz",
    "Fire Quartz",
    "Frozen Tear",
    "Earth Crystal",
    "Emerald",
    "Aquamarine",
    "Ruby",
    "Amethyst",
    "Topaz",
    "Jade",
    "Diamond",
    "Prismatic Shard",
    "Alamite",
    "Bixite",
    "Baryte",
    "Aerinite",
    "Calcite",
    "Dolomite",
    "Esperite",
    "Fluorapatite",
    "Geminite",
    "Helvite",
    "Jamborite",
    "Jagoite",
    "Kyanite",
    "Lunarite",
    "Malachite",
    "Neptunite",
    "Lemon Stone",
    "Nekoite",
    "Orpiment",
    "Petrified Slime",
    "Thunder Egg",
    "Pyrite",
    "Ocean Stone",
    "Ghost Crystal",
    "Tigerseye",
    "Jasper",
    "Opal",
    "Fire Opal",
    "Celestine",
    "Marble",
    "Sandstone",
    "Granite",
    "Basalt",
    "Limestone",
    "Soapstone",
    "Hematite",
    "Mudstone",
    "Obsidian",
    "Slate",
    "Fairy Stone",
    "Star Shards",
    "Apple Sapling",
    "Apricot Sapling",
    "Cherry Sapling",
    "Orange Sapling",
    "Peach Sapling",
    "Pomegranate Sapling",
    "Banana Sapling",
    "Mango Sapling",
    "Apple",
    "Apricot",
    "Cherry",
    "Orange",
    "Peach",
    "Pomegranate",
    "Banana",
    "Mango",
    "Amaranth Seeds",
    "Artichoke Seeds",
    "Beet Seeds",
    "Jazz Seeds",
    "Blueberry Seeds",
    "Bok Choy Seeds",
    "Cactus Seeds",
    "Cauliflower Seeds",
    "Coffee Bean",
    "Corn Seeds",
    "Cranberry Seeds",
    "Eggplant Seeds",
    "Fairy Seeds",
    "Garlic Seeds",
    "Grape Starter",
    "Bean Starter",
    "Hops Starter",
    "Pepper Seeds",
    "Kale Seeds",
    "Melon Seeds",
    "Parsnip Seeds",
    "Pineapple Seeds",
    "Poppy Seeds",
    "Potato Seeds",
    "Pumpkin Seeds",
    "Radish Seeds",
    "Red Cabbage Seeds",
    "Rhubarb Seeds",
    "Starfruit Seeds",
    "Strawberry Seeds",
    "Spangle Seeds",
    "Sunflower Seeds",
    "Rare Seed",
    "Taro Tuber",
    "Tomato Seeds",
    "Tulip Bulb",
    "Rice Shoot",
    "Wheat Seeds",
    "Yam Seeds",
    "Amaranth",
    "Artichoke",
    "Beet",
    "Blue Jazz",
    "Blueberry",
    "Bok Choy",
    "Cauliflower",
    "Corn",
    "Cranberries",
    "Eggplant",
    "Fairy Rose",
    "Garlic",
    "Grape",
    "Green Bean",
    "Hops",
    "Hot Pepper",
    "Kale",
    "Melon",
    "Parsnip",
    "Pineapple",
    "Poppy",
    "Potato",
    "Pumpkin",
    "Radish",
    "Red Cabbage",
    "Rhubarb",
    "Starfruit",
    "Strawberry",
    "Summer Spangle",
    "Sunflower",
    "Sweet Gem Berry",
    "Taro Root",
    "Tomato",
    "Tulip",
    "Unmilled Rice",
    "Wheat",
    "Yam",
    "Ancient Fruit",
    "Algae Soup",
    "Artichoke Dip",
    "Baked Fish",
    "Bean Hotpot",
    "Blackberry Cobbler",
    "Blueberry Tart",
    "Cheese Cauliflower",
    "Chocolate Cake",
    "Chowder",
    "Complete Breakfast",
    "Crab Cakes",
    "Cranberry Candy",
    "Crispy Bass",
    "Dish O' The Sea",
    "Eggplant Parmesan",
    "Escargot",
    "Farmer's Lunch",
    "Fiddlehead Risotto",
    "Fish Taco",
    "Fried Calamari",
    "Fried Eel",
    "Fried Egg",
    "Fried Mushroom",
    "Fruit Salad",
    "Ginger Ale",
    "Glazed Yams",
    "Hashbrowns",
    "Maki Roll",
    "Maple Bar",
    "Miner's Treat",
    "Omelet",
    "Pale Broth",
    "Pancakes",
    "Parsnip Soup",
    "Pepper Poppers",
    "Pink Cake",
    "Plum Pudding",
    "Poppyseed Muffin",
    "Pumpkin Pie",
    "Red Plate",
    "Rhubarb Pie",
    "Rice Pudding",
    "Roasted Hazelnuts",
    "Roots Platter",
    "Salmon Dinner",
    "Sashimi",
    "Stir Fry",
    "Stuffing",
    "Survival Burger",
    "Tortilla",
    "Tropical Curry",
    "Vegetable Medley"
]