class Animal:
    chicken = "Chicken"
    cow = "Cow"
    pig = "Pig"
    duck = "Duck"
    sheep = "Sheep"
    dinosaur = "Dinosaur"
    rabbit = "Rabbit"
    goat = "Goat"
    ostrich = "Ostrich"
    void_chicken = "Void Chicken"
    golden_chicken = "Golden Chicken"
    sve_camel = "Camel"
    sve_bear = "Bear"
    sve_goose = "Goose"
