class Character:
    sir_bunalot = "Sir Bunalot"
    scrappy = "Scrappy"
    felina = "Felina"
    count_clawcula = "Count Clawcula"
    dolly = "Dolly"
    benny_beaver = "Benny Beaver"
    bernie = "Bernie"
    squiddy = "Squiddy"
    garbage_greg = "Garbage Greg"
    anne_bunny = "Anne Bunny"
    hare_l_quinn = "Hare L. Quinn"
    chief_bunner = "Chief Bunner"
    cuddline_floofington = "Cuddline Floofington"
